//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Инфо фото.
    /// </summary>
    // *** Start programmer edit section *** (ИнфоФото CustomAttributes)

    // *** End programmer edit section *** (ИнфоФото CustomAttributes)
    [AutoAltered()]
    [Caption("Инфо фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИнфоФотоE", new string[] {
            "Категория as \'Категория\'",
            "Цена as \'Цена\'"})]
    [AssociatedDetailViewAttribute("ИнфоФотоE", "ДопНастройки", "ДопНастройкиE", true, "", "Доп настройки", true, new string[] {
            ""})]
    [View("ИнфоФотоL", new string[] {
            "Категория as \'Категория\'",
            "Цена as \'Цена\'"})]
    public class ИнфоФото : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Fotokiosk2.Категория fКатегория;
        
        private int fЦена;
        
        private IIS.Fotokiosk2.DetailArrayOfДопНастройки fДопНастройки;
        
        // *** Start programmer edit section *** (ИнфоФото CustomMembers)

        // *** End programmer edit section *** (ИнфоФото CustomMembers)

        
        /// <summary>
        /// Категория.
        /// </summary>
        // *** Start programmer edit section *** (ИнфоФото.Категория CustomAttributes)

        // *** End programmer edit section *** (ИнфоФото.Категория CustomAttributes)
        public virtual IIS.Fotokiosk2.Категория Категория
        {
            get
            {
                // *** Start programmer edit section *** (ИнфоФото.Категория Get start)

                // *** End programmer edit section *** (ИнфоФото.Категория Get start)
                IIS.Fotokiosk2.Категория result = this.fКатегория;
                // *** Start programmer edit section *** (ИнфоФото.Категория Get end)

                // *** End programmer edit section *** (ИнфоФото.Категория Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнфоФото.Категория Set start)

                // *** End programmer edit section *** (ИнфоФото.Категория Set start)
                this.fКатегория = value;
                // *** Start programmer edit section *** (ИнфоФото.Категория Set end)

                // *** End programmer edit section *** (ИнфоФото.Категория Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ИнфоФото.Цена CustomAttributes)

        // *** End programmer edit section *** (ИнфоФото.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (ИнфоФото.Цена Get start)

                // *** End programmer edit section *** (ИнфоФото.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (ИнфоФото.Цена Get end)

                // *** End programmer edit section *** (ИнфоФото.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнфоФото.Цена Set start)

                // *** End programmer edit section *** (ИнфоФото.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ИнфоФото.Цена Set end)

                // *** End programmer edit section *** (ИнфоФото.Цена Set end)
            }
        }
        
        /// <summary>
        /// Инфо фото.
        /// </summary>
        // *** Start programmer edit section *** (ИнфоФото.ДопНастройки CustomAttributes)

        // *** End programmer edit section *** (ИнфоФото.ДопНастройки CustomAttributes)
        public virtual IIS.Fotokiosk2.DetailArrayOfДопНастройки ДопНастройки
        {
            get
            {
                // *** Start programmer edit section *** (ИнфоФото.ДопНастройки Get start)

                // *** End programmer edit section *** (ИнфоФото.ДопНастройки Get start)
                if ((this.fДопНастройки == null))
                {
                    this.fДопНастройки = new IIS.Fotokiosk2.DetailArrayOfДопНастройки(this);
                }
                IIS.Fotokiosk2.DetailArrayOfДопНастройки result = this.fДопНастройки;
                // *** Start programmer edit section *** (ИнфоФото.ДопНастройки Get end)

                // *** End programmer edit section *** (ИнфоФото.ДопНастройки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИнфоФото.ДопНастройки Set start)

                // *** End programmer edit section *** (ИнфоФото.ДопНастройки Set start)
                this.fДопНастройки = value;
                // *** Start programmer edit section *** (ИнфоФото.ДопНастройки Set end)

                // *** End programmer edit section *** (ИнфоФото.ДопНастройки Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИнфоФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнфоФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнфоФотоE", typeof(IIS.Fotokiosk2.ИнфоФото));
                }
            }
            
            /// <summary>
            /// "ИнфоФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИнфоФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИнфоФотоL", typeof(IIS.Fotokiosk2.ИнфоФото));
                }
            }
        }
    }
}
