//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Fotokiosk2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сделать фото.
    /// </summary>
    // *** Start programmer edit section *** (СделатьФото CustomAttributes)

    // *** End programmer edit section *** (СделатьФото CustomAttributes)
    [AutoAltered()]
    [Caption("Сделать фото")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СделатьФотоE", new string[] {
            "КолВоФото as \'Кол во фото\'",
            "ИнфоФото as \'Инфо фото\'",
            "ИнфоФото.Категория as \'Категория\'",
            "ИнфоФото.Цена"}, Hidden=new string[] {
            "ИнфоФото.Категория"})]
    [MasterViewDefineAttribute("СделатьФотоE", "ИнфоФото", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Категория")]
    [View("СделатьФотоL", new string[] {
            "КолВоФото as \'Кол во фото\'",
            "ИнфоФото.Категория as \'Категория\'"})]
    public class СделатьФото : ICSSoft.STORMNET.DataObject
    {
        
        private int fКолВоФото;
        
        private IIS.Fotokiosk2.ИнфоФото fИнфоФото;
        
        // *** Start programmer edit section *** (СделатьФото CustomMembers)

        // *** End programmer edit section *** (СделатьФото CustomMembers)

        
        /// <summary>
        /// КолВоФото.
        /// </summary>
        // *** Start programmer edit section *** (СделатьФото.КолВоФото CustomAttributes)

        // *** End programmer edit section *** (СделатьФото.КолВоФото CustomAttributes)
        public virtual int КолВоФото
        {
            get
            {
                // *** Start programmer edit section *** (СделатьФото.КолВоФото Get start)

                // *** End programmer edit section *** (СделатьФото.КолВоФото Get start)
                int result = this.fКолВоФото;
                // *** Start programmer edit section *** (СделатьФото.КолВоФото Get end)

                // *** End programmer edit section *** (СделатьФото.КолВоФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СделатьФото.КолВоФото Set start)

                // *** End programmer edit section *** (СделатьФото.КолВоФото Set start)
                this.fКолВоФото = value;
                // *** Start programmer edit section *** (СделатьФото.КолВоФото Set end)

                // *** End programmer edit section *** (СделатьФото.КолВоФото Set end)
            }
        }
        
        /// <summary>
        /// Сделать фото.
        /// </summary>
        // *** Start programmer edit section *** (СделатьФото.ИнфоФото CustomAttributes)

        // *** End programmer edit section *** (СделатьФото.ИнфоФото CustomAttributes)
        [PropertyStorage(new string[] {
                "ИнфоФото"})]
        [NotNull()]
        public virtual IIS.Fotokiosk2.ИнфоФото ИнфоФото
        {
            get
            {
                // *** Start programmer edit section *** (СделатьФото.ИнфоФото Get start)

                // *** End programmer edit section *** (СделатьФото.ИнфоФото Get start)
                IIS.Fotokiosk2.ИнфоФото result = this.fИнфоФото;
                // *** Start programmer edit section *** (СделатьФото.ИнфоФото Get end)

                // *** End programmer edit section *** (СделатьФото.ИнфоФото Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СделатьФото.ИнфоФото Set start)

                // *** End programmer edit section *** (СделатьФото.ИнфоФото Set start)
                this.fИнфоФото = value;
                // *** Start programmer edit section *** (СделатьФото.ИнфоФото Set end)

                // *** End programmer edit section *** (СделатьФото.ИнфоФото Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СделатьФотоE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СделатьФотоE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СделатьФотоE", typeof(IIS.Fotokiosk2.СделатьФото));
                }
            }
            
            /// <summary>
            /// "СделатьФотоL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СделатьФотоL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СделатьФотоL", typeof(IIS.Fotokiosk2.СделатьФото));
                }
            }
        }
    }
}
